### ISSUE TITLE
JCchess running on Windows 64 bit operation systems

### ISSUE THREAD

**Issue by yellow-panther** [johncheetham/jcchess#1]
Hello John,

does it only require **PyGObject for Windows**
https://sourceforge.net/projects/pygobjectwin32 - **Python 3.62. for Windows 64 bit** https://www.python.org/ftp/python/3.6.2/python-3.6.2-amd64-webinstall.exe or is **an installation of further software necessary to run this application?**

I tried PyGObject for Windows, but an error occured:
**Setup cant find supported Python registry**

installation path is **C:\Programme\Python 36**

What´s about Python Chess Library https://github.com/niklasf/python-chess ?

**Comment by gbtami** [comment]
@yellow-panther pygobject doesn't support nor Python 3.5 nor 3.6 yet.
"PyGI 3.24.1 AIO rev1 for python 2.7, 3.1, 3.2, 3.3 and 3.4 (32bit/64bit)"

I suggest to install Python 3.4.4 first from https://www.python.org/downloads/release/python-344/
because newer 3.4.x releases are source only.

Then install latest PyGI from https://sourceforge.net/projects/pygobjectwin32/files/
When installing it you have to check packages:
  Base packages
  GDK-Pixbuf
  GTK+ 3.x
  Pango

Finally from command line window:
git clone https://github.com/johncheetham/jcchess.git

From jcchess dir you can run it now like:
python run.py

p.s.: You have nothing to do with python-chess. jcchess source contains an earlier version of it inside.

**Comment by johncheetham** [comment]
Thanks gbtami for those instructions.
I haven't tried it myself on windows but I did manage to run gshogi (on which jcchess is based) on it a while back so hopefully it should work.

**Comment by johncheetham** [comment]
I tried this and it works OK for me on windows 7 64 bit.
I've added step by step instructions to the git repo (see the file Readme-windows.txt.)
yellow-panther can you try following the instructions in the Readme-windows.txt file and see if it works for you.

**Comment by johncheetham** [comment]
Windows builds are now available on the website and I have updated the git repo with the files/instructions for creating the installers using pynsist.
